# This file was generated by GoReleaser. DO NOT EDIT.
cask "typeburn" do
  version "2.8.1"

  on_macos do
    on_intel do
      sha256 "dabf0b70bd313eb672c22f7a393e41b81971e65b0400667327d70d81d32959e3"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "94c5e422d37c8e1b305fddf149a822cc6f9ccefd97bfa643227c8b992ccc28eb"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7b02663c2f2b964075938b4785d79dcc79c49064176247c21c5e83f1a9691c8c"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "566e9dfa18ec84791ead87d318f5e2fd37442348746cf21cfec21e146ba131e2"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "typeburn"
  desc "A Monkeytype-style terminal typing test, distraction-free and keyboard-driven."
  homepage "https://github.com/bavanchun/Typeburn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "typeburn"

  # No zap stanza required

end
