# This file was generated by GoReleaser. DO NOT EDIT.
cask "typeburn" do
  version "2.1.1"

  on_macos do
    on_intel do
      sha256 "f0bea3883aa5740a73d7370d2168d34ecc4cacabf49e25ef9a7264acda44c7c0"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1680511da67c154ed41580a685cbc6b6cc0b65f69378c856f8b2762b39850cbc"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "767500e06e673e68558f66c02b690cb8aeb3a0844a8c77574b12659d20f46031"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b2b58e53533df999f92672d851f9c114825eda104d4039fa1886f5d63534d7f"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "typeburn"
  desc "A Monkeytype-style terminal typing test, distraction-free and keyboard-driven."
  homepage "https://github.com/bavanchun/Typeburn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "typeburn"

  # No zap stanza required

end
