# This file was generated by GoReleaser. DO NOT EDIT.
cask "typeburn" do
  version "2.9.0"

  on_macos do
    on_intel do
      sha256 "b99703e1c6ea02674be430223fe6caddf58f2cbdbbcd9232a38fee49718d0991"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e5b4a93050e65d4930b9555b517ab83860bc6b51892acb86cc2323ec972be724"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb7674a1e07d1f960547afd5738225f8cc1ab1f179cadc5a2ac2a4267a57c64d"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a5338c965694606b563b0d710576cef33a36583641a2800b2a895e509f0253b4"
      url "https://github.com/bavanchun/Typeburn/releases/download/v#{version}/typeburn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "typeburn"
  desc "A Monkeytype-style terminal typing test, distraction-free and keyboard-driven."
  homepage "https://github.com/bavanchun/Typeburn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "typeburn"

  # No zap stanza required

end
